__Creating a new data frame__

In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame()

In [2]:
df.shape

(0, 0)

In [3]:
data = [[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]]
data = np.array(data)
data = data.reshape(2,-1)
columns = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
#columns = np.array(columns)
#columns = columns.reshape(1,-1)
df = pd.DataFrame(data, columns=columns)

In [4]:
df.shape

(2, 7)

In [5]:
df

Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
0       1       2        3          4         5       6         7
1       7       6        5          4         3       2         1

In [6]:
data = {'Sunday':[1,2,3], 'Monday':[1,2,3]}
df = pd.DataFrame(data)

In [7]:
df

Sunday  Monday
0       1       1
1       2       2
2       3       3

In [8]:
for i, j in data.items():
    print(i,j)

Sunday [1, 2, 3]
Monday [1, 2, 3]


__creating data frame from list of dictionaries__

In [9]:
data = [{'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7}]
df = pd.DataFrame(data)

In [10]:
df

Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
0       1       2        3          4         5       6         7
1       1       2        3          4         5       6         7
2       1       2        3          4         5       6         7

In [11]:
data = [{'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7}]
df = pd.DataFrame(data, index=['First','Second','Third'])

In [12]:
df

Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
First        1       2        3          4         5       6         7
Second       1       2        3          4         5       6         7
Third        1       2        3          4         5       6         7

In [13]:
df1 = df['Sunday']

In [14]:
df1

First     1
Second    1
Third     1
Name: Sunday, dtype: int64

__Vectors, Arrays, and Matrices__</br>
__vectors__ : With respect to python, Vectors in simple words, can be considered as a single dimension array of list. But it does not have row and column elements. It is same as a list in structure but it differes widely in terms of its usability and working.</br>
__Vector Dot Product__:</br>

The vector dot product performs between the two same-length sequential vectors and returns the single dot product. We will use the .dot() method to perform the dot product. It will happen as below.</br>
vector c = x . y = (x1 * y1 + x2 * y2)  

In [15]:
import numpy as np   
   
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  
   
vtr1 = np.array(list1)   
   
vtr2= np.array(list2)   
   
print("We create vector from a list 1:")   
print(vtr1)   
print("We create a vector from a list 2:")   
print(vtr2)   
  
vtr_product = vtr1.dot(vtr2)  
print("Dot product of two vectors: ",vtr_product)  

We create vector from a list 1:
[10 20 30 40 50]
We create a vector from a list 2:
[5 2 4 3 1]
Dot product of two vectors:  380


#But we cannot perform the same operation in python list:
   
list1 = [10,20,30,40,50]   
list2 = [5,2,4,3,1]  

lst_product = list1.dot(list2)  
print("Dot product of two vectors: ",lst_product)  

AttributeError: 'list' object has no attribute 'dot'. 

In machine learning we will have to perform these kind of operations for many reasons. So vector is one of the necessay data structure in python.

__Shape of a vector__:</br>
The shpae() function returns the tuple containing the number and rows for array. But when used with vector or 1-d array it only returns the size of that vector, not row or column. </br>
(a,) = means vector has a number of elements. </br>
if it is the case of 1d array, then we can manipulate it as array has 5 rows and 1 column.

In [16]:
list1 = [10,20,30,40,50] 
v1 = np.array(list1)
v1.shape

(5,)

</br>

__Array__:
What are Python Arrays?</br>
Arrays are a fundamental data structure, and an important part of most programming languages. In Python, they are containers which are able to store more than one item at the same time.
</br>
Specifically, they are an ordered collection of elements with every value being of the same data type. That is the most important thing to remember about Python arrays - the fact that they can only hold a sequence of multiple items that are of the same type.</br>


__What's the Difference between Python Lists and Python Arrays?__</br>
Lists are one of the most common data structures in Python, and a core part of the language.</br>

Lists and arrays behave similarly.</br>

Just like arrays, lists are an ordered sequence of elements.
</br>
They are also mutable and not fixed in size, which means they can grow and shrink throughout the life of the program. Items can be added and removed, making them very flexible to work with.
</br>
However, lists and arrays are not the same thing.
</br>
Lists store items that are of various data types. This means that a list can contain integers, floating point numbers, strings, or any other Python data type, at the same time. That is not the case with arrays.
</br>
As mentioned in the section above, arrays store only items that are of the same single data type. There are arrays that contain only integers, or only floating point numbers, or only any other Python data type you want to use.
</br>
__When to Use Python Arrays__
Lists are built into the Python programming language, whereas arrays aren't. Arrays are not a built-in data structure, and therefore need to be imported via the array module in order to be used.
</br>
Arrays of the array module are a thin wrapper over C arrays, and are useful when you want to work with homogeneous data.
</br>
They are also more compact and take up less memory and space which makes them more size efficient compared to lists.
</br>
__If you want to perform mathematical calculations, then you should use NumPy arrays by importing the NumPy package. Besides that, you should just use Python arrays when you really need to, as lists work in a similar way and are more flexible to work with.__


__.shape()</br>
The numpy module provides a shape function to represent the shape and size of an array. The shape of an array is the no. of elements in each dimension.</br>
In NumPy, we will use a function called shape that returns a tuple, the elements of the tuple give the lengths of the array dimensions.</br>
The shape attribute always returns a tuple that represents the length of each dimension. The 1-d array is a row vector and its shape is a single value sequence followed by a comma.__

In [17]:
data = [{'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7},
       {'Sunday':1,'Monday':2,'Tuesday':3,'Wednesday':4,'Thursday':5,'Friday':6,'Saturday':7}]
df = pd.DataFrame(data)

df1 = df['Sunday'] #Actually here, df1 is a series which is also an array.

df1.shape

(3,)

In [18]:
df1 = [1,2,3,4,5,6,7]
df1 = np.array(df1)

df1.shape

(7,)

The shape (7,) implies that df1 is a 1d array which is a row vector which means it is not in the format of row and column. So it does not return number of rows and number of columns. But we can understand the value in tuple as the number of itmes present in that 1d array or row verctor in single direction</br>
</br>
__df1 = 1d vector__

In [19]:
df1

array([1, 2, 3, 4, 5, 6, 7])

Now we want to reshape our array containing single row and multiple columns

In [20]:
df1 = df1.reshape(1,-1) #Single row and any number of columns

In [21]:
df1

array([[1, 2, 3, 4, 5, 6, 7]])

In [22]:
df1.shape

(1, 7)

In [23]:
df1 = df1.reshape(7,1) # 7 rows and 1 column

In [24]:
df1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [25]:
df1.shape

(7, 1)

In [26]:
df1=df1.reshape(-1,1) # Any number of rows and single column

In [27]:
df1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [28]:
df1 = df1.reshape(1,-1) #single row and any number of columns
df1

array([[1, 2, 3, 4, 5, 6, 7]])

__2D Array__

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) #Two rows and 4 columns

(2, 4)


In [30]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Selecting elements in vector, array or matrix.

In [31]:
#create row vector
vector = np.array([1,2,3,4,5,6])
vector[2] # accessing the items at 2th position in vector. Position 
#starts from 0.

3

In [32]:
vector[:] # accessing all elements inside the vector. ":" does al lot of work.

array([1, 2, 3, 4, 5, 6])

In [33]:
vector[:3] # accessing all elements upto the 3 position, excluding the itm at 3 position.
#it will return items at 0, 1 and 2.

array([1, 2, 3])

In [34]:
vector[3:] # accessing all elements from 3 position to the last position

array([4, 5, 6])

In [35]:
vector[-1] # accessing the last element

6

In [36]:
vector[:-1]# accessing all elements from first to last excluding the last one

array([1, 2, 3, 4, 5])

In [37]:
vector[::-1]# accessing all elements from last to first including the last one

array([6, 5, 4, 3, 2, 1])

In [38]:
vector[-1:] # returning the last element as a array value

array([6])

# Accessing elements inside the matrix

__Matrix__</br>
Matrix is a special case of two dimensional array where each data element is of strictly same size. So every matrix is also a two dimensional array but not vice versa.
</br>
Matrices are very important data structures for many mathematical and scientific calculations.
</br>
__Creating a Matrix__
Use NumPy to create a two-dimensional array:</br>
To create a matrix we can use a NumPy two-dimensional array. In our solution, the matrix contains three rows and two columns (a column of 1s and a column of 2s).



In [39]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [40]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [41]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [42]:
# Select second row, second column
matrix[1,1]

5

In [43]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

</br>

</br>

</br>


</br>

__Pandas Series__</br>
The pandas documentation defines a Series as -</br>
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.
</br>
And if multiple series are combined with one single index, it is known as “data frame”. In other words, a data frame is a collection of series having the same index.</br>
</br>
__list index vs series index__

In [45]:
lst1 = ['a','b','c','d',5]
lst1  #by default the index of items in increasing order from 0 to len-1.
#We change the items at certain index but cannot cange the index itself.
#second index will always come after the 1st index.


['a', 'b', 'c', 'd', 5]

In [ ]:
lst1[0], lst1[1]

In [ ]:
lst1 = ['b','a','c','d',5]
lst1[0], lst1[1]

__In list we assign items to the index__: that means we can place items in our desired index. For example we can change the index of 'd' to 0.</br>
__But in series we can assign the index to the item__: for example: 

In [ ]:
ser1 = pd.Series(lst1, index=[3,2,4,1,0])
ser1

__We assigned the items in list to different indices in series__
</br>
__Series will always have index value by default. List will also have index value by default but we cant manipulate the index value of list as we can do in series. That is the main difference between list and series in python.__ </br>
We can bring the row placed in 100th position to the 1st position by simply assigning it new index value in seres.

In [ ]:
df0 = pd.DataFrame(ser1, columns=['Data'])

In [ ]:
df0

In [ ]:
lst2 = [2,4,5,5,'X']
ser2 = pd.Series(lst2, index=[3,2,4,1,0])
ser2

In [ ]:
data = {'Ser1':ser1, 'ser2':ser2}

In [ ]:
import pandas as pd
  

# # create a dictonary

data = {'Ser1':ser1,
        'ser2':ser2}

# Concatenating the series side
# by side as depicted by axis=1
# If you want to concatenate the 
# series one below the other
# change the axis to zero.
df = pd.concat(data,
               axis = 1)
  
# show the dataframe
df

</br>

__iloc in python__</br>
The iloc() function in python is one of the functions defined in the Pandas module that helps us to select a specific row or column from the data set. Using the iloc() function in python, we can easily retrieve any particular value from a row or column using index values.
</br>
</br>
__Syntax of iloc() function in Python__
The syntax of the iloc() function in python is very simple. We can invoke the iloc() function in python on the data set to retrieve rows and columns. As:</br>
pandas. dataset.iloc[row, column] 
</br>
</br>
__Parameters of iloc() function in Python__
The iloc function in python takes two parameters, however, both of the parameters to the iloc() method is optional. Let us discuss both of these parameters:</br>

__row__: row parameter is an optional parameter that specifies the index position of the row in the form of an integer or list of integers.</br>
__column__: column parameter is also an optional parameter that specifies the index position of the column in the form of an integer or list of integers.</br>

__Return Value of iloc() function in Python__
Using the parameters provided, the iloc() function in python returns a data set or series. The return value changes according to the parameters provided in the iloc function in python:</br>

If we specify only one value i.e. only row value then the iloc() function in python returns a Pandas Series.</br>
If we specify two values i.e. row value and column value then the iloc function in python returns all the content of the specified cell. If we specify a list of values, then python's iloc function returns a Pandas DataFrame.






In [ ]:
df = pd.read_csv('Titanic.csv')

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.iloc[2,:] #2nd row all columns

In [ ]:
df.iloc[1,1] # first row first column

In [ ]:
d = df.iloc[:,1] #All rows from the second column which is at position 1

In [ ]:
d

In [ ]:
d = df.iloc[0:100,0:5] #Only accessing 100 rows for 5 columns

In [ ]:
d

</br>

</br>

# Generating Random Values using numpy's random:


In [ ]:
import numpy as np


In [ ]:
# Set seed
np.random.seed(0)


In [ ]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

In [ ]:
# Generate 'n' random integers between a and b, including a and excluding b
#np.random.randint(a,b,n)
c = np.random.randint(0,2,10)

In [ ]:
c

In [ ]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

In [ ]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(-10, 20, 30)

np.random.random(a) takes only one argument. It generates 1d row vector containing 'a' number of elements.</br>
But np.random.rand(a,b) generates multidimensional array having a number of rows and b number of columns

In [ ]:
#generates the floating point randomly between 0 and 1 in given dimension
d= np.random.rand(1) #only one item
d

In [ ]:
d= np.random.rand(1,5) #1 row 5 column
d

In [ ]:
d= np.random.rand(2,2) #2 row 2 column
d

In [ ]:
d= np.random.rand(2,2,2) # 3 d array, i.e 2 array each one containing
#2 different array of size 2 rows and 2 columns
d

np.random.rand(a,b,c) </br>
a = number of arrays
b = rows in each array
c column of each array

In [ ]:
d = np.random.rand(3,2,3) #3 array, each one containing 2 array of having
#2 rows and 3 columns
d

In [ ]:
dic1 = {'A':1, 'B':2}
df = pd.DataFrame(dic1, index=[0,1])

In [ ]:
df

In [ ]:
data = np.random.randint(0,10,20)

columns = ['A','B','C','D','E','F','G','H','I','J']
data=data.reshape(2,-1)

In [ ]:
df = pd.DataFrame(data, columns =columns)

In [ ]:
df

In [ ]:
dic1 = {'Name':['Ram','Shyam'], 'Age':[22,22]}
dic1

In [ ]:
df = pd.DataFrame(dic1)

In [ ]:
df

In [ ]:
#creating dictionary containing list
name = ['Ram','Shyam', 'Hari']
addr = ['KTM','LTPR', 'BHKTPR']
age = [20,21,22]
dic1 = {'Name':name, 'Address':addr, 'Age':age}
dic1

In [ ]:
df = pd.DataFrame(dic1, index=[1,2,3])

In [ ]:
df